---

- name: Ensure user groups
  set_fact:
    uid: "0"
  when: item.key == "root"
 
- name: Ensure user groups
  set_fact:
    uid: "{{ item.value.uid }}"
  when: item.key != "root"

- name: Ensure user exists
  ansible.builtin.user:
    name: "{{ item.key }}"
    comment: "{{ item.value.fullname }}"
    uid: "{{ uid }}"
    shell: /bin/bash
    state: present

- name: Set subuid
  ansible.builtin.lineinfile:
    path: "/etc/subuid"
    regex: "^{{ item.key}}:" 
    line: "{{ item.key }}:{{ item.value.subuid }}:65536"
  when: item.value.subuid is defined

- name: Set subgid
  ansible.builtin.lineinfile:
    path: "/etc/subgid"
    regex: "^{{ item.key}}:" 
    line: "{{ item.key }}:{{ item.value.subuid }}:65536"
  when: item.value.subuid is defined

- name: Ensure user groups
  ansible.builtin.user:
    name: "{{ item.key }}"
    groups: "{{ item.value.groups }}"
  when: item.value.groups is defined

- name: Add bashrc lines
  become_user: "{{ item.key }}"
  ansible.builtin.lineinfile:
    path: "${HOME}/.bashrc"
    regex: "{{ bash_line.regexp }}" 
    line: "{{ bash_line.line }}" 
  loop:
    - { regexp: "^alias ll='ls -l'", line: "alias ll='ls -l'" }
  loop_control:
    loop_var: bash_line

- name: Deploy SSH Public Key
  ansible.posix.authorized_key:
    user: "{{ item.key }}"
    state: present
    key: "{{ lookup('file', '{{ item.value.keyFile }}') }}"
  when: item.value.keyFile is defined
