---

- name: Setup auto rsync backup on USB disk plug via udev
  become: true
  block:
    - name: Create systemd override directory for systemd-udevd
      file:
        path: /etc/systemd/system/systemd-udevd.service.d
        state: directory
        mode: '0755'

    - name: Create systemd service for USB backup
      copy:
        dest: /etc/systemd/system/{{ backup.server_name }}-backup@.service
        content: |
          [Unit]
          Description=Backup to external drive %i
          After=dev-%i.device
          BindsTo=dev-%i.device

          [Service]
          Type=oneshot
          ExecStartPre=/bin/sleep 5
          ExecStart=/opt/scripts/backup-system.sh /dev/%I
          User=root
          Group=root

          [Install]
          WantedBy=dev-%i.device
        mode: '0644'

    - name: Ensure /opt/scripts directory exists
      file:
        path: /opt/scripts
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Deploy backup script
      template:
        src: backup-system.sh.j2
        dest: /opt/scripts/backup-system.sh
        mode: '0755'
        owner: root
        group: root

    - name: Create the udev rule
      blockinfile:
        path: /etc/udev/rules.d/99-{{ backup.server_name }}-usb-rsync-backup.rules
        create: true
        marker: "# {mark} ANSIBLE MANAGED BLOCK - EXTERNAL DISK BACKUP"
        block: |
          ACTION=="add", SUBSYSTEM=="block", ENV{DEVTYPE}=="partition", ENV{ID_SERIAL}=="{{ backup.external_drive.serial }}", ENV{SYSTEMD_WANTS}="{{ backup.server_name }}-backup@%k.service"

    - name: Reload systemd
      systemd:
        daemon_reload: true

    - name: Reload udev rules
      command: udevadm control --reload-rules
