---
- name: Hello
  ansible.builtin.import_tasks: hello.yml
  tags: [hello]

- name: Raid mount task
  ansible.builtin.import_tasks: raid.yml
  tags: [raid]

- name: Install samba
  ansible.builtin.import_tasks: samba.yml
  tags: [samba]

- name: Prepare networking
  ansible.builtin.import_tasks: network.yml
  tags: [network]

- name: Install lxc
  ansible.builtin.import_tasks: lxc.yml
  tags: [lxc]

- name: Install rootless docker
  ansible.builtin.import_tasks: rootless-docker-installation.yml
  vars:
    username: "rootless"
  tags: [docker]

- name: Setup Backups
  ansible.builtin.import_tasks: backup.yml
  tags: [backup]

- name: Install home-assistant
  ansible.builtin.import_tasks: homeassistant-kvm.yml
  tags: [homeassistant]
