---
# tasks file for debian
  - name: Install dependencies
    ansible.builtin.apt:
      pkg:
      - mdadm

  - name: Search RAID partitions
    shell: mdadm --assemble --scan --verbose
    register: mdadm_result
    failed_when: mdadm_result.rc != 2


  - name: Add partitions to fstab
    include_tasks: "raid/fstab.yml"
    with_dict: "{{ raid_partitions }}"
    when: raid_partitions is defined

  - name: Mount all added partitions
    shell: mount -a
