---
# tasks file for debian


  - name: Echo partiton mount points and ids
    ansible.builtin.debug:
      msg: "{{ item.key }} - {{ item.value }}"
    with_dict: "{{ raid_partitions }}"
    when: raid_partitions is defined