---
- name: Adding docker repository 
  shell: |
    install -m 0755 -d /etc/apt/keyrings
    rm /etc/apt/keyrings/docker.gpg
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo \
      "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
      "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null


- name: Installing dependencies
  apt:
    update_cache: yes
    pkg:
      - docker-ce-rootless-extras
      - docker-compose
      - uidmap

- name: Rootless docker installation
  become: true
  become_user: rootless
  shell: curl -fsSL https://get.docker.com/rootless | sh

- name: Add docker bin path to PATH
  ansible.builtin.lineinfile:
    path: /home/rootless/.bashrc
    regex: "{{ item.regexp }}" 
    line: "{{ item.line }}" 
  loop:
    - { regexp: '^export XDG_RUNTIME_DIR=', line: "export XDG_RUNTIME_DIR=/home/rootless/.docker/run" }
    - { regexp: '^export PATH=$PATH:$HOME/bin', line: "export PATH=$PATH:$HOME/bin" }
    - { regexp: '^export DOCKER_HOST=', line: "export DOCKER_HOST=unix:///home/rootless/.docker/run/docker.sock" }