---
- name: Adding docker repository
  shell: |
    install -m 0755 -d /etc/apt/keyrings
    rm /etc/apt/keyrings/docker.gpg
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo \
      "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
      "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null


- name: Installing dependencies
  apt:
    update_cache: yes
    pkg:
      - dbus-user-session
      - docker-ce-rootless-extras
      - docker-compose
      - fuse-overlayfs
      - systemd-container
      - uidmap

- name: Rootless docker installation
  become: true
  become_user: "{{ username}}"
  shell: curl -fsSL https://get.docker.com/rootless | sh

- name: Add docker bin path to PATH
  become: true
  become_user: "{{ username}}"
  ansible.builtin.lineinfile:
    path: /home/{{ username}}/.bashrc
    regex: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^export XDG_RUNTIME_DIR=', line: "export XDG_RUNTIME_DIR=/home/{{ username}}/.docker/run" }
    - { regexp: '^export PATH=$PATH:$HOME/bin', line: "export PATH=$PATH:$HOME/bin" }
    - { regexp: '^export DOCKER_HOST=', line: "export DOCKER_HOST=unix:///run/user/$UID/docker.sock" }

- name: Fix dockerd rootless installation script
  become: true
  become_user: "{{ username}}"
  ansible.builtin.replace:
    path: /home/{{ username}}/bin/dockerd-rootless-setuptool.sh
    regexp: "unix://\\$.*XDG_RUNTIME_DIR.*/docker.sock"
    replace: "unix:///run/user/$(id -u $(whoami))/docker.sock"


- name: Touch sysctl conf
  shell: touch /etc/sysctl.d/99-rootless.conf 

- name: Generate sysctl conf
  include_tasks: "subtasks/rootless-sysctl.yml"
  with_dict: |
    {{ '{
        "net.ipv6.conf.all.disable_ipv6" : "1",
        "net.ipv6.conf.default.disable_ipv6" : "1",
        "net.ipv6.conf.lo.disable_ipv6" : "1",
        "net.ipv4.ping_group_range" : "0 2147483647",
        "net.ipv4.ip_unprivileged_port_start" : "80"
    }' | from_json }}

- name: Start docker user service for the user rootless
  become: true
  become_user: "{{ username}}"
  become_method: machinectl 
  ansible.builtin.shell: |
    /home/{{ username}}/bin/dockerd-rootless-setuptool.sh install
    systemctl enable --user --now docker


- name: Setup rootless docker autostart at login with daemon reload
  ansible.builtin.shell: |
    loginctl enable-linger {{ username}}
    sysctl --system
