---
- name: Add docker apt repository
  ansible.builtin.shell: |
    set -euo pipefail
    install -m 0755 -d /etc/apt/keyrings
    rm -f /etc/apt/keyrings/docker.gpg
    curl -fsSL https://download.docker.com/linux/debian/gpg \
      | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg]" \
      "https://download.docker.com/linux/debian" \
      "$(. /etc/os-release && echo "$VERSION_CODENAME")" \
      "stable" \
      | tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: Install rootless docker dependencies
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - dbus-user-session
      - docker-ce-rootless-extras
      - docker-compose
      - fuse-overlayfs
      - systemd-container
      - uidmap

- name: Rootless docker installation
  become: true
  become_user: "{{ username }}"
  ansible.builtin.shell: curl -fsSL https://get.docker.com/rootless | sh
  args:
    creates: "/home/{{ username }}/bin/dockerd-rootless-setuptool.sh"

- name: Add docker bin path to PATH
  become: true
  become_user: "{{ username }}"
  ansible.builtin.lineinfile:
    path: "/home/{{ username }}/.bashrc"
    regex: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - {
        regexp: "^export XDG_RUNTIME_DIR=",
        line: "export XDG_RUNTIME_DIR=/home/{{ username }}/.docker/run",
      }
    - {
        regexp: '^export PATH=\$PATH:\$HOME/bin',
        line: "export PATH=$PATH:$HOME/bin",
      }
    - {
        regexp: "^export DOCKER_HOST=",
        line: "export DOCKER_HOST=unix:///run/user/$UID/docker.sock",
      }

- name: Fix dockerd rootless installation script
  become: true
  become_user: "{{ username }}"
  ansible.builtin.replace:
    path: "/home/{{ username }}/bin/dockerd-rootless-setuptool.sh"
    regexp: "unix://\\$.*XDG_RUNTIME_DIR.*/docker.sock"
    replace: "unix:///run/user/$(id -u $(whoami))/docker.sock"

- name: Generate sysctl conf
  ansible.builtin.include_tasks: subtasks/rootless-sysctl.yml
  loop:
    - {
        key: "net.ipv6.conf.all.disable_ipv6",
        value: "1",
      }
    - {
        key: "net.ipv6.conf.default.disable_ipv6",
        value: "1",
      }
    - {
        key: "net.ipv6.conf.lo.disable_ipv6",
        value: "1",
      }
    - {
        key: "net.ipv4.ping_group_range",
        value: "0 2147483647",
      }
    - {
        key: "net.ipv4.ip_unprivileged_port_start",
        value: "80",
      }

- name: Install and enable rootless docker user service
  become: true
  become_user: "{{ username }}"
  become_method: machinectl
  ansible.builtin.shell: |
    /home/{{ username }}/bin/dockerd-rootless-setuptool.sh install
    systemctl enable --user --now docker
  args:
    creates: "/home/{{ username }}/.config/systemd/user/docker.service"

- name: Enable lingering for {{ username }}
  ansible.builtin.command: loginctl enable-linger {{ username }}
  args:
    creates: "/var/lib/systemd/linger/{{ username }}"

- name: Apply sysctl
  ansible.builtin.command: sysctl --system
  changed_when: false
