---
# tasks file for debian
  - name: Install packages
    ansible.builtin.apt:
      pkg:
        - build-essential
        - ca-certificates
        - curl
        - fish
        - git-all
        - golang
        - golang-doc
        - gnupg
        - gpg
        - hd-idle
        - jq
        - tldr
        - tmux
        - vim
        - wget

  - name: hd-idle configuration
    ansible.builtin.lineinfile:
      path: /etc/default/hd-idle
      regex: "^#HD_IDLE_OPTS="
      line: "HD_IDLE_OPTS=\"-i 180 -l /var/log/hd-idle.log\""
  
  - name: Enable hd-idle service
    ansible.builtin.systemd:
      name: hd-idle
      state: started
      enabled: true

  - name: Users and groups task
    ansible.builtin.include_tasks: users-and-groups.yml