---
- name: Add mount line to fstab
  ansible.builtin.lineinfile:
    dest: /etc/fstab
    regexp: '^{{ item.value.partition | regex_escape }}\s'
    line: "{{ item.value.partition }}\t{{ item.key }}\t{{ item.value.file_system_type }}\tdefaults\t0\t2"
    state: present
  register: fstab_line

- name: Create mount folder
  ansible.builtin.file:
    path: "{{ item.key }}"
    state: directory
    owner: root
    group: root
    mode: '0775'
  when: fstab_line.changed
