---
- name: Set sysctl {{ item.key }}={{ item.value }}
  ansible.builtin.lineinfile:
    create: true
    dest: /etc/sysctl.d/99-rootless.conf
    regexp: '^{{ item.key | regex_escape }}='
    line: '{{ item.key }}={{ item.value }}'
    mode: '0644'
